language: node_js
node_js:
  - "0.12"
services:
  - mongodb
before_script:
  - npm install -g grunt-cli
  - npm install
  - node ./lib/account_generator.js
script:
  - "pm2 start ./bin/www"
  - npm start