module.exports = function  (str1, str2) {
	var strVar="";
strVar += "<!DOCTYPE html >";
strVar += "<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">";
strVar += " <head>";
strVar += "  <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\" \/>";
strVar += "  <title>Email template<\/title>";
strVar += "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"\/>";
strVar += "  <link href=\"http:\/\/fonts.googleapis.com\/css?family=Lato:Light 300\" rel=\"stylesheet\" type=\"text\/css\">";
strVar += "<\/head>";
strVar += "<body style=\"margin: 0; padding: 0;font-family:'Tahoma'\">";
strVar += " <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-collapse: collapse;\">";
strVar += "  <tr>";
strVar += "   <td bgcolor=\"#ffffff\">";
strVar += "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">";
strVar += " <tr>";
strVar += "  <td width=\"260\" valign=\"top\">";
strVar += "   <img src=\"http:\/\/s3.amazonaws.com\/viands\/images_welcome\/Viands_logo.jpg\" width=\"100%\" height=\"180px;\">";
strVar += "  <\/td>";
strVar += "  <td style=\"font-size: 0; line-height: 0;\" width=\"20\">";
strVar += "   &nbsp;";
strVar += "  <\/td>";
strVar += "  <td width=\"260\" valign=\"top\">";
strVar += "   <img src=\"http:\/\/s3.amazonaws.com\/viands\/images_welcome\/Ogara_logo.jpg\" width=\"100%\" height=\"180px\">";
strVar += "  <\/td>";
strVar += " <\/tr>";
strVar += "<\/table>";
strVar += "   <\/td>";
strVar += "  <\/tr>";
strVar += "  <tr>";
strVar += "   <td bgcolor=\"#ffffff\" style=\"padding:40px 20px 40px 30px;\">";
strVar += "    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">";
strVar += "    	<tr>";
strVar += "          <td style=\"padding:25px 10px 20px 20px;\">";
strVar += "          Dear Sir,  ";
strVar += str1;
strVar += "\n";
strVar += str2;
strVar += "          <\/td>";
strVar += "    	<\/tr>";
strVar += "    	<tr>";
strVar += "          <td style=\"padding:10px 5px 20px 20px;\">";
strVar += "            ";
strVar += "          <\/td>";
strVar += "    	<\/tr>";
strVar += "    	<tr>";
strVar += "          <td style=\"padding:10px 10px 20px 20px;\">";
strVar += "          ";
strVar += "          <\/td>";
strVar += "    	<\/tr>";
strVar += "    <tr>";
strVar += "<td style=\"padding:10px 10px 20px 20px;\">";
strVar += "";
strVar += "<\/td>";
strVar += "    <\/tr>";
strVar += "    <tr>";
strVar += "<td style=\"padding:10px 10px 20px 20px;\">";
strVar += "Contact us at <a href=\"\">contactus@viands.in<\/a>.";
strVar += "<\/td>";
strVar += "    <\/tr>";
strVar += "    <tr>";
strVar += "<td style=\"padding:10px 10px 20px 20px;\">";
strVar += "Best,<br>";
strVar += "The Viands Team";
strVar += "<\/td>";
strVar += "    <\/tr>";
strVar += "    <\/table>";
strVar += "    <hr>";
strVar += "   <\/td>";
strVar += "  <\/tr>";
strVar += "  	<tr>";
strVar += "<td style=\"text-align:center;font-weight:bold;\">";
strVar += "Powered by,";
strVar += "<\/td>";
strVar += "  	<\/tr>";
strVar += "  <tr>";
strVar += "   <td bgcolor=\"#ffffff\" style=\"padding-top:-20px;\">";
strVar += "    <img src=\"http:\/\/s3.amazonaws.com\/viands\/images_welcome\/one100solutions_logo.png\" width=\"50%\" height=\"230px;\" style=\"display:block;margin-left:auto;margin-right:auto;\"> ";
strVar += "   <\/td>";
strVar += "  <\/tr>";
strVar += " <\/table>";
strVar += "<\/body>";
strVar += "<\/html>";
return strVar;
}