module.exports = function () {

  var html = [
'<!DOCTYPE html >',
'<html xmlns="http://www.w3.org/1999/xhtml">',
' <head>',
'  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />',
'  <title>Email template</title>',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>',
'  <link href="http://fonts.googleapis.com/css?family=Lato:Light 300" rel="stylesheet" type="text/css">',
'</head>',
'<body style="margin: 0; padding: 0;font-family:"Tahoma"">',
' <table align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse;">',
'  <tr>',
'   <td bgcolor="#ffffff">',
'    <table border="0" cellpadding="0" cellspacing="0" width="100%">',
' <tr>',
'  <td width="260" valign="top">',
'   <img src="http://s3.amazonaws.com/viands/images_welcome/Viands_logo.jpg" width="100%" height="180px;">',
'  </td>',
'  <td style="font-size: 0; line-height: 0;" width="20">',
'   &nbsp;',
'  </td>',
'  <td width="260" valign="top">',
'   <img src="http://s3.amazonaws.com/viands/images_welcome/ogara_campus_cafe.jpg" width="100%" height="180px">',
'  </td>',
' </tr>',
'</table>',
'   </td>',
'  </tr>',
'  <tr>',
'   <td bgcolor="#ffffff" style="padding:40px 20px 40px 30px;">',
'    <table border="0" cellpadding="0" cellspacing="0" width="100%">',
'     <tr>',
'          <td style="padding:25px 10px 20px 20px;">',
'            Greetings from Viands.',
'          </td>',
'     </tr>',
'     <tr>',
'          <td style="padding:10px 5px 20px 20px;">',
'            Thank you for signing up with us. We are here to make your experience at RV"s Food Court better.',
'          </td>',
'     </tr>',
'     <tr>',
'          <td style="padding:10px 10px 20px 20px;">',
'            Viands aim to address the excessive time spent during ordering and then collecting one"s order at the always busy Food ',
'Court counters. Via this app, you can know your food, pre-order your meal, enjoy various offers on food items etc.',
'          </td>',
'     </tr>',
'    <tr>',
'<td style="padding:10px 10px 20px 20px;">',
'<button style="border-radius:5px;background-color:#f7772a;height:40px;width:75%;margin:auto;margin-left:45px;text-align:center;font-size:20px;color:#ffffff;overflow:hidden:"><a href="http://www.viands.in" style="text-decoration:none;color:#fff;">Click here to go to our website.</a></button>',
'</td>',
'    </tr>',
'    <tr>',
'<td style="padding:10px 10px 20px 20px;">',
'Contact us at <a href="">contactus@viands.in</a>.',
'</td>',
'    </tr>',
'    <tr>',
'<td style="padding:10px 10px 20px 20px;">',
'Best,<br>',
'The Viands Team',
'</td>',
'    </tr>',
'    </table>',
'    <hr>',
'   </td>',
'  </tr>',
'   <tr>',
'<td style="text-align:center;font-weight:bold;">',
'Powered by,',
'</td>',
'   </tr>',
'  <tr>',
'   <td bgcolor="#ffffff" style="padding-top:-20px;">',
'    <img src="http://s3.amazonaws.com/viands/images_welcome/one100solutions_logo.png" width="50%" height="230px;" style="display:block;margin-left:auto;margin-right:auto;"> ',
'   </td>',
'  </tr>',
' </table>',
'</body>',
'</html>'
].join('');

return html;
}